name: CI Standard Checks
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
jobs:
  ci-standard-checks:
    uses: Typeform/.github/.github/workflows/ci-standard-checks-workflow.yaml@v1
