name: Secrets Scan

on: [push, pull_request]

jobs:
  secrets-scan:
    # for public repositories
    runs-on: [ubuntu-latest]
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Secrets Scan
        uses: Typeform/.github/shared-actions/secrets-scan@master
        with:
          docker-registry: ${{ secrets.GITLEAKS_DOCKER_REGISTRY }}
          docker-username: ${{ secrets.GITLEAKS_DOCKER_USERNAME }}
          docker-password: ${{ secrets.GITLEAKS_DOCKER_PASSWORD }}
          gh-token: ${{ secrets.GH_TOKEN }}
