name: Visual Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  visual:
    runs-on: ubuntu-latest
    # skip for external PRs, run for push on main branch
    if: ${{ !github.event.pull_request || github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Get yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ~/.cache
          key: ${{ runner.os }}-repo-${{ github.event.pull_request.head.repo.full_name }}-node-16-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('.github/workflows/**.yml') }}

      - name: Install Node.js dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - run: yarn build

      - run: yarn test:visual
        env:
          VRT_APIURL: ${{ secrets.VRT_APIURL }}
          VRT_APIKEY: ${{ secrets.VRT_APIKEY }}
          VRT_PROJECT: ${{ secrets.VRT_PROJECT }}
          VRT_BRANCHNAME: ${{ github.head_ref || github.ref_name }}
          VRT_CIBUILDID: ${{ github.sha }}
